### ISSUE TITLE
Link to CDCL missing

### ISSUE THREAD

**Issue by JulianKunkel** [IO500/webpage#10]
Clicking on a list element links to the detail page.
A link to the data center list should be included on the detail page prominently.

E.g. for DKRZ:
https://www.jbez.io500.org/site/releases/view/130

**Comment by johnbent** [comment]
Nice idea.  Do we have a mapping between submissions and data center list entries?  Julian, if you can provide this list please, then Jean Luca can you add this please?

**Comment by jeanbez** [comment]
@JulianKunkel do you have this list so we can add?

**Comment by JulianKunkel** [comment]
Hi, the list of URLs is in the CSV file created like this:
[https://www.vi4io.org/io500/list/20-11/historic?fields=information__system,information__institution,information__storage_vendor,information__filesystem_type,information__client_nodes,information__client_total_procs,io500__score,io500__bw,io500__md,information__data,information__list_id,information__URL&equation=&sort_asc=false&sort_by=io500__score&radarmax=6&query=#](url)

**Comment by jeanbez** [comment]
@JulianKunkel just to confirm, the idea is that once we open a submission detailed page, we have a button that will open the VI4IO page for that site, such as this one: https://www.vi4io.org/hpsl/2018/usa/ornl/start 

Is this correct?

**Comment by JulianKunkel** [comment]
Yes, there should be a (new) link to the VI4IO, a button would do nicely.
