### ISSUE TITLE
hyperlinks on webpage not easily visible

### ISSUE THREAD

**Issue by adilger** [IO500/webpage#114]
The hyperlinks on webpages that use the "< ? php echo $this->Html->link ...>" method appear the same color as the text (e.g. "call for submissions" and "Press release for April 14, 2021" on the "news" page, or the links under "Further Reading" on the "about" page) so it is difficult to know that these are actually links.

Hyperlinks that are using the "< a class="link" href=...>" style appear with a red text color which make it clear they are links.

The "< ? php ...>" links should also be highlighted with a separate color, presumably red, so that they can more easily be seen.

**Comment by jeanbez** [comment]
@adilger I believe this has been fixed and merged, so we could close this issue.
