### ISSUE TITLE
"Valid" column is political difficult

### ISSUE THREAD

**Issue by JulianKunkel** [IO500/webpage#12]
Using the term "valid" for a column may not be optimal.

**Comment by johnbent** [comment]
Would you prefer changing it to 'Accepted' or 'Unaccepted'?  The design doc did discuss this and talked about how we can track 'invalid' results and allow users to click on the submission for an explanation of the 'invalidity' which would be something like, "It was determined that caching was in effect" or "the md-test hard write phase did not last for the requisite 300 seconds."

**Comment by jeanbez** [comment]
@JulianKunkel can we close this issue or do we need to change something?
