### ISSUE TITLE
Remove duplicates in custom lists by default

### ISSUE THREAD

**Issue by adilger** [IO500/webpage#149]
It would be very helpful to allow removal of duplicate storage system results from custom lists.  This would allow comparison of systems more easily, and _should_ allow recreation of the main ranked+sorted lists using a custom equation (e.g. just "io500_bw" or "io500_md" as the equation).

I'm thinking just a checkbox like "filter duplicate results" or "one/best result per storage system" or similar.

**Comment by seattleplus** [comment]
Further to this, we had discussed in the past that on the 'customize' page, the default list shown should be the official io500 list and not the full list.  This would filter out the duplicates by default.  Then to add what Andreas is saying, we could have options to add the duplicates back in through some options for 'io500 list', 'full list', etc.
