### ISSUE TITLE
Custom list example not working with isc21

### ISSUE THREAD

**Issue by Danile71** [IO500/webpage#158]
![image](https://user-images.githubusercontent.com/2876826/124240422-69c83980-db23-11eb-850e-c5148a05a607.png)

**Comment by jeanbez** [comment]
@Danile71 Thank you for reporting it. I believe this issue has been fixed, could you confirm?

**Comment by Danile71** [comment]
> @Danile71 Thank you for reporting it. I believe this issue has been fixed, could you confirm?

Yes, thanks!
