### ISSUE TITLE
IO500 Scores missing IOPS value

### ISSUE THREAD

**Issue by gflofst** [IO500/webpage#168]
Click on an entry (such as Pengchang on the home page) and scroll down to the box labeled IO500 Scores. In there, the IOPS score is 0.0. It is also that on the Endeavour submission. This may be a general problem.

**Comment by jeanbez** [comment]
Yes, it seems that all submissions from ISC21 do not have that information. I checked and the original spreadsheet also do not have those values.

**Comment by gflofst** [comment]
@adilger @seattleplus @JulianKunkel @gmarkomanolis What do we want to do about this?

**Comment by gmarkomanolis** [comment]
what is the source of the problem? If can not be avoided, remove this field from the web page for SC21 submissions and later?

**Comment by gflofst** [comment]
I think the results generator is either leaving those blank on the input or there is some other problem. Since the raw data didn't have it, but the website did, I expected that it was ignored. I don't know the purpose.

**Comment by JulianKunkel** [comment]
I do not know what the IOPS score should be.
We had used scoreBW and scoreMD afaik.

**Comment by jeanbez** [comment]
We removed this score in https://github.com/IO500/webpage/pull/189
