### ISSUE TITLE
Change the storage type of data server

### ISSUE THREAD

**Issue by sock3212007** [IO500/webpage#230]
Hello,
   I‘m Song Ke from China Telecom Research Institute.Our IO500 sore ranks 29th in the 10 node list of sc22:
   
![image](https://user-images.githubusercontent.com/16346133/205002790-7e2e935e-1f79-4033-ace8-5e47491efac5.png)
But we want to change the storage type of data server with our SSD vendor 'memblaze'.  Could you help us?:
![image](https://user-images.githubusercontent.com/16346133/205003179-60cdf0b1-2463-4ee2-ae88-7cd1c0b72af9.png)

**Comment by adilger** [comment]
The "storage type" field is not a specific vendor.  In this case PMEM means "Persistent Memory" and given the NVDIMM interface is the correct type, so I don't think any change is needed here. Cheers, AndreasOn Dec 1, 2022, at 08:27, sock3212007 ***@***.***> wrote:﻿
Hello,
I‘m Song Ke from China Telecom Research Institute.Our IO500 sore ranks 29th in the 10 node list of sc22:

But we want to change the storage type of data server with our SSD vendor 'memblaze'.  Could you help us?:
