### ISSUE TITLE
Remove "Browse Files" button "Download Zip" button in submitted files along with its display section.

### ISSUE THREAD

**Issue by kaushikvelusamy** [IO500/webpage#237]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/3243744/227012412-4a178503-706a-4f06-9e6f-13ced0ae1018.png">

Only "Browse in Github" Remains

**Comment by kaushikvelusamy** [comment]
@jeanbez : Could you test this PR in your linux setup once before merging?

**Comment by jeanbez** [comment]
@kaushikvelusamy  yes, however I could not find the PR. Could you point to the link?

**Comment by jeanbez** [comment]
@kaushikvelusamy can you open the PR? I could not find it, thanks!

**Comment by kaushikvelusamy** [comment]
https://github.com/IO500/webpage/pull/254
