### ISSUE TITLE
Mechanism to backup database and audit changes

### ISSUE THREAD

**Issue by adilger** [IO500/webpage#32]
To maintain the database in case of server failure it is desirable to have an offsite backup that is not connected to the web/database host.  It would also be desirable for research purposes if the database can be easily exported/imported by others (subject to data embargo before the release of the next list).  Finally, it would be useful to be able to audit any changes to the database that are changing the metadata related to a submission (e.g. adding RAM per server, correcting devices per node vs. total devices, etc).

One possible solution for this is to use a MySQL->Git exporting tool to dump the database as a series of SQL statements (e.g. one line per record, sorted in a consistent manner to ensure consistency between backups, via `mysqldump -u [user] -p[pass] --skip-extended-insert [database]` or similar, maybe a separate file for each table), and then check the resulting text file into Git after each dump.  That can make it very clear to human reviewers when new records are added, or when existing records are modified.  Having the database in Git ensures that past versions of the database can be verified and recovered easily (e.g. in case of compromise and vandalism) also allows anyone to clone the database easily and import the data into another SQL database without any special permission or access to the host, allowing backups by multiple users.  See https://www.viget.com/articles/backup-your-database-in-git/ for example.

**Comment by adilger** [comment]
Julian created a sample `mysqldump` in the io500-database repository.

This has a simple 'sed' script to modify the input to be one line per database row, so that it is clear which entries are being modified.  That would allow Git to ignore entries/lines that have no modifications.

However, it appears that the dump is sorted by the io500 score, and has a "index" at the beginning, which is not suitable for using with Git because the "index" of every "slower" entry would change whenever a new entry is added.  Instead, the mysqldump ordering should use some fixed key (e.g. increasing submission date) so that new entries are added at the end, and the only time earlier lines appear in a `git diff` is if the line was modified for some reason.

If it isn't possible to achieve this consistent ordering by using mysqldump, it could possibly be done with text-processing tools so that it sorts the `submissions` table by a specific field (e.g. `sort -t, -k16`) and then uses `sed` or `awk` to rewrite the "index" field with the new ordering before saving the file to Git.

**Comment by jeanbez** [comment]
@adilger I believe this has been addressed as well, when we implemented the approval of SQL modifications before running in the DB, correct? Do you want to include something else, or we can close this issue?
