### ISSUE TITLE
Add more prominent links to system info generator

### ISSUE THREAD

**Issue by johnbent** [IO500/webpage#40]
Can someone please stick the system information generator page somewhere on the rules and/or submission page? I can never find it.

Thanks to Ken Carlisle for suggesting this.

**Comment by JulianKunkel** [comment]
I hope we resolve this when reconsidering the schema (for the next list) and then implementing the new version on io500.org.

**Comment by jeanbez** [comment]
@JulianKunkel do you have an update on this?
