### ISSUE TITLE
CRITICAL: Ranked lists contain entries where users disagreed to be listed

### ISSUE THREAD

**Issue by JulianKunkel** [IO500/webpage#54]
In the submission form, users could manually select if they wish to be listed in the ranked list for 10 Node challenge and the IO500 list, it appears that at the moment just all entries are listed.
We must fix this immediately as we committed to honor the wishes of submitters.
There are many reasons why a submitter may decide not to be listed.
Please compare the lists at VI4IO or the JSON if in doubt.

**Comment by johnbent** [comment]
Thanks Julian. Can you please provide a list of the submissions which requested to be excluded?

**Comment by JulianKunkel** [comment]
It's included in the json as field "list"
https://www.vi4io.org/assets/io500/2020-11-all-x/data.json

**Comment by johnbent** [comment]
So for example, this is one that you’re saying should not be in ranked list:

    "information": {
        "id":"2020-11-2",
	"submission_date": "2020-10-30",
        "list_id": "sc20",
        "version" : "io500-sc20",
        "data": "2020-10-30-JaneliaResearchCampusHowardHughesMedicalInstitutewekafsParallelFilesystem-10-32.zip",
        "submitter": "Janelia Scientific Computing Systems",
        "list": "",

**Comment by JulianKunkel** [comment]
Yes.

There are many 10 nodes that don't want to be listed in the io500 list. As
this one is slower than another submission it doesn't matter if 10node is
selected or not.


John Bent <notifications@github.com> schrieb am So., 8. Nov. 2020, 20:06:

**Comment by johnbent** [comment]
Submission with score 161.53 should be 'exclude_from_ranked'.

**Comment by jeanbez** [comment]
@JulianKunkel and @johnbent the three entries in the JSON file that should not be displayed in the new website were updated. We can close this isse!

**Comment by johnbent** [comment]
From Julian: “ @John Bent (he/him/his) Two submissions from me that shouln't be in the Io500 list: https://io500.org/site/submissions/view/474 and https://io500.org/site/submissions/view/472“

**Comment by adilger** [comment]
fixed via pr #82
