### ISSUE TITLE
Create io500.org/sc20bof page for live event info

### ISSUE THREAD

**Issue by gflofst** [IO500/webpage#58]
According to our video uploaded to SC, we told people to go to
https://io500.org/sc20bof

This needs a link to the blackboard, new slack

Also needs info about how to use blackboard (Julian to provide)

**Comment by johnbent** [comment]
Thanks @gflofst , do you have a link to the blackboard yet?

**Comment by jeanbez** [comment]
I've gone ahead and created the template for the page based on previous versions. We just need to include the new information.

https://github.com/IO500/webpage/pull/60

**Comment by gflofst** [comment]
No. That is why I assigned to @JulianKunkel.

**Comment by adilger** [comment]
They've started sending out info about how to manage the BOFs. I'm getting such emails, but am unsure if they relate to the IO500 or the Lustre BOF that I'm also on. 

The use of Blackboard should only be a fallback if we are unable to use the official channels, IMHO, or it seems possible that we could be banned from participating in future SC events.
