### ISSUE TITLE
List release overview page + vertical navigation

### ISSUE THREAD

**Issue by JulianKunkel** [IO500/webpage#63]
For an issue, we had good overview pages such as
http://io500.org/list/20-11/
Please add back an overview page, e.g., allow direct navigation between a page such as:
https://io500.org/site/submissions/list/sc19
To other lists such as:
https://io500.org/site/submissions/ten/sc19

Please also create a short URL back:
http://io500.org/list/20-11/
Instead of:
https://io500.org/site/submissions/list/sc19

**Comment by jeanbez** [comment]
About the short URL we have issue #80 to solve as it will require to reorganize the server structure.

**Comment by jeanbez** [comment]
@JulianKunkel this has also been solved and merged, so I am closing this issue.
