### ISSUE TITLE
duplication of system and missing 10node result

### ISSUE THREAD

**Issue by carlilek** [IO500/webpage#69]
I have a system that appears on both the 10node and the official lists multiple times because I changed the names. For Janelia Research Campus, HHMI, the weka and sharedscratch entries are the same system. Preferred name would be sharedscratch, but whatever is the easiest to implement is fine.  

Additionally, My SC20 submission for that system (labelled as weka) was not included in the 10node list, although it appears on the all submissions list: 
https://io500.org/site/submissions/view/464

that should supercede this one on the 10node: 
https://io500.org/site/submissions/view/102

**Comment by carlilek** [comment]
Found another missing one: 
https://io500.org/site/submissions/view/473

should supercede 
https://io500.org/site/submissions/view/163

on the 10node list for SC20

**Comment by johnbent** [comment]
Thanks @carlilek !  @jeanbez , can you help resolve this please?

**Comment by jeanbez** [comment]
Submissions have been updated
