### ISSUE TITLE
Unspecified values in custom equation inherit values from previous entry

### ISSUE THREAD

**Issue by adilger** [IO500/webpage#73]
Originally from issue #25, the value of the custom equation is not being calculated correctly in all cases.

For example, if the divisor is zero because the fields are unset then it appears to be using the fields from the previous entry in the list:
![88716554-760a7200-d0dc-11ea-8f5e-93afa49c90c0](https://user-images.githubusercontent.com/167584/99609992-2ecb2880-29ce-11eb-8815-638a15626e77.png)

In the Shaheen case, the divisor is 4, which also appears to be the value from the previous entry in the list.

It isn't clear to me whether the calculated result should be "infinity" in this case, and ranked at the top of the list, or if it should be excluded completely? In the VI4IO ranking, I was able to multiply the zero in the numerator, so the result was zero before dividing by zero (NaN) which ranked at the end of the list. It would be nice to have a checkbox like "exclude invalid results" (i.e. Inf and NaN), or allow booleans like "( information_ds_nodes + information_md_nodes > 0 ) *" so the result is multiplied by 0 if the expression isn't true.

**Comment by jeanbez** [comment]
@adilger I believe we can close this issue as it was already resolved and merged, correct?

**Comment by adilger** [comment]
Yes, it looks like the calculations are being done correctly now, or at least it is not showing invalid values when I tried the above equation `io500_score / (information_md_nodes + information_ds_nodes)` (which would result in a divide-by-zero if the field is unset).  It now prints `Sorry, but there was an error creating the custom list!`.
