### ISSUE TITLE
Missing 10-node result (SC’20)

### ISSUE THREAD

**Issue by alberto-miranda** [IO500/webpage#75]
The SC'20 "10-node challenge entry" for EPCC's NEXtGenIO system (with GekkoFS) is missing, despite correctly appearing in the full SC'20 list with a score of 239.37.

**Comment by alberto-miranda** [comment]
Belay that, I just noticed it's already there... I swear it wasn't when I checked 20' ago 🤨

**Comment by alberto-miranda** [comment]
Reopening because even though there is indeed an entry, the information reported therein is wrong. My confusion came because the old vi4io page shows the correct information.

**Comment by jeanbez** [comment]
Submission has been updated to show in the SC20 10-node list.
