### ISSUE TITLE
ARCHER2 result missing from the 10 node sc20 list

### ISSUE THREAD

**Issue by adrianjhpc** [IO500/webpage#76]
Not my result, but it looks like the ARCHER2 result should be included on the top500 10 node list but it isn't currently there.

**Comment by JulianKunkel** [comment]
Can you confirm that it is correctly in the list here:
https://www.vi4io.org/io500/list/20-11/10node

**Comment by adrianjhpc** [comment]
Yes, looks fine there.

**Comment by jeanbez** [comment]
Submission has been updated to show in the 10 node SC20 list.

**Comment by adilger** [comment]
fixed
