### ISSUE TITLE
Improve the process: Any changes to the webpage must be approved by the committee.

### ISSUE THREAD

**Issue by JulianKunkel** [IO500/webpage#77]
Implement processes that ensure that DB changes are monitored and approved by all members. 
Integrate the SQL dump and prevent any manual changes to any file on the webserver including the DB.

**Comment by adilger** [comment]
I think this would be covered by issue #32.

**Comment by JulianKunkel** [comment]
I agree that there is a clear link and that #32 resolves the DB part. 
Still this is a top issue that reminds us to follow the agreed rules:
https://io500.org/site/rules-committee
We should ensure to audit any change to the webpage to prevent any mistake.

**Comment by adilger** [comment]
Julian, I don't know if there is anything specific here that can be "fixed" beyond what is in issue #32 to track the database.

The rest of the website is already in Github and is already reviewed before landing.

I think this issue should just be closed.

**Comment by adilger** [comment]
Julian, any objection to closing this and using issue #32 to track the SQL database backup/audit?
