### ISSUE TITLE
Inconsistency in Historical list vs. VI4IO list

### ISSUE THREAD

**Issue by adilger** [IO500/webpage#92]
Comparing the [IO500 Historical list] (https://io500.org/site/submissions/historical/sc20) against the equivalent  [VI4IO Historical list](https://www.vi4io.org/io500/list/20-11/historic?fields=information__system,information__institution,information__storage_vendor,information__filesystem_type,information__client_nodes,information__client_total_procs,io500__score,io500__bw,io500__md,information__data,information__list_id&equation=&sort_asc=false&sort_by=io500__score&radarmax=6&query=) it looks like the IO500 list has only 153 entries vs. 245. 

The historical list is intended to show all entries that were ever submitted. It looks like the the first missing entry is the isc19 University of Cambridge Data Capacitor, ranked 12 on the VI4IO list.

**Comment by adilger** [comment]
Jean Luca, did you ever get a chance to look into this?

**Comment by jeanbez** [comment]
I'm still checking, hope to finish it this week.

**Comment by jeanbez** [comment]
@adilger how is the historical list supposed to handle the entries that were invalidated/corrected through time? Should it display both records (the original, and the correct), or only the corrected one? Could you clarify this? I believe this is what is causing the mismatch in my local tests now.

**Comment by JulianKunkel** [comment]
I would think that only one should be shown. Can you give an example where
this causes trouble?

**Comment by adilger** [comment]
Jean Luca, I think this depends on what you mean by "corrected".  I believe separate submissions from a site should be listed separately (ie. no duplicate filtering), which is independent of the process of editing some fields of a submission due to error/incomplete data (which would affect the original submission, and I don't think we should keep a separate copy of the original in the database).

**Comment by jeanbez** [comment]
The way things are today, if we need to correct something, that would spawn a new record in the `submissions` table with the correct information, marking it as `valid_from` from today onward. The original one is updated with a `valid_to` up until this moment. We need this 'duplication' to keep displaying the old lists consistently. That was the case with the list from SC18* @JulianKunkel. We have two records in the database for them: the original one and the one where the score was corrected.

In this sense, today's historical list would be listing both records, as it should be by the description of the list: all submissions ever received, including the invalid ones (as the full list only filter the valid). Suggestions on how should we proceed?

**Comment by adilger** [comment]
I don't think there are (m)any cases where we would want to modify the score of a submission.  I think the main cause for modifying a submission would be editing metadata (e.g. number of servers, storage type, etc.).  In those cases, we would want to update this information in the old lists as well.

**Comment by adilger** [comment]
Verified that the two lists are matching.

**Comment by adilger** [comment]
oops, i was checking the to-be-released website is valid...
